apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "healthchecks.fullname" . }}
  labels:
    {{- include "healthchecks.labels" . | nindent 4 }}
data:
  uwsgi.ini: |+
    {{- .Values.uwsgi.ini | nindent 4 }}
